# Numpy: Package for Multidimensional array
## Vector(1d)
## Matrix(2d or 1d)

## Create an array

In [3]:
import numpy as np

In [4]:
sample_list=[6,7,9]
np.array(sample_list)

array([6, 7, 9])

In [8]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [9]:
matrix=([1,2,3],[4,5,6],[7,8,9])
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
matrix1=([12,15,26,33],[93,45,76,73],[22,45,66,77],[94,32,65,11])
np.array(matrix1)

array([[12, 15, 26, 33],
       [93, 45, 76, 73],
       [22, 45, 66, 77],
       [94, 32, 65, 11]])

In [14]:
np.arange(5,28)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27])

In [15]:
np.arange(5,35,6)

array([ 5, 11, 17, 23, 29])

In [16]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

In [18]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [21]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [22]:
np.ones((4,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [29]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [34]:
np.linspace(0,20,11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [35]:
np.linspace(0,10,15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [37]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [40]:
np.random.rand(2,4)

array([[0.03713968, 0.24168264, 0.85211201, 0.10595875],
       [0.0795767 , 0.47406356, 0.33571836, 0.17518027]])

In [44]:
np.random.rand(3,4)

array([[0.38778093, 0.51242768, 0.86295457, 0.34428619],
       [0.08673527, 0.04276342, 0.26173296, 0.56917831],
       [0.66717907, 0.906738  , 0.06162534, 0.54906741]])

In [42]:
np.random.randn(2,4)

array([[-0.07580335,  0.76691785,  0.95242   ,  0.25456288],
       [ 0.69212638, -0.0363608 ,  0.96648996, -2.4103629 ]])

In [45]:
np.random.randn(2,3)

array([[ 0.78741267, -1.93060752, -1.64850707],
       [ 0.43727949,  1.06505479,  0.23082836]])

In [48]:
np.random.randint(0,10,15)

array([8, 3, 4, 4, 8, 2, 5, 9, 9, 0, 3, 2, 2, 6, 5])

In [49]:
np.random.randint(10,100,15)

array([66, 38, 11, 12, 55, 35, 21, 13, 28, 41, 56, 12, 57, 92, 11])

In [50]:
np.random.randint(20,56,100)

array([20, 25, 36, 48, 55, 29, 23, 49, 35, 22, 27, 26, 45, 29, 21, 38, 48,
       37, 55, 48, 34, 23, 21, 52, 50, 25, 26, 25, 20, 23, 47, 24, 26, 49,
       34, 20, 53, 45, 27, 25, 42, 39, 53, 36, 41, 45, 41, 49, 36, 24, 39,
       47, 29, 38, 29, 53, 30, 22, 20, 23, 45, 25, 43, 53, 37, 27, 38, 44,
       20, 52, 34, 34, 28, 36, 49, 55, 52, 52, 43, 29, 50, 22, 29, 35, 49,
       35, 30, 45, 42, 40, 27, 39, 47, 43, 33, 31, 31, 50, 29, 55])

In [52]:
sample_array=np.arange(2,20)
sample_array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [54]:
rand_array=np.random.randint(0,10,5)
rand_array

array([3, 5, 4, 0, 3])

In [55]:
sample_array.min()

2

In [56]:
rand_array.min()

0

In [57]:
sample_array.argmin()

0

In [58]:
rand_array.argmin()

3

In [59]:
rand_array.max()

5

In [60]:
rand_array.argmax()

1

In [61]:
sample_array.argmax()

17

In [62]:
sample_array.dtype

dtype('int32')

In [63]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [65]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [66]:
a=np.random.rand(2,3)
a

array([[0.82563638, 0.27059508, 0.67149828],
       [0.12692844, 0.85321221, 0.99257303]])

In [67]:
a.T

array([[0.82563638, 0.12692844],
       [0.27059508, 0.85321221],
       [0.67149828, 0.99257303]])

In [16]:
sample_array=np.arange(10,28)
sample_array


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27])

In [17]:
sample_array=sample_array.reshape(3,6)
sample_array

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27]])

In [20]:
sample_array=sample_array.reshape(3,4)
sample_array

ValueError: cannot reshape array of size 18 into shape (3,4)

In [21]:
sample_array[1]=100
sample_array

array([[ 10,  11,  12,  13,  14,  15],
       [100, 100, 100, 100, 100, 100],
       [ 22,  23,  24,  25,  26,  27]])

In [23]:
sample_array=np.arange(10,100)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [24]:
sample_array[1:12]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [27]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [29]:
sample_array[:]=1001
sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001])

## Two-dimensional array

In [30]:
import numpy as np

In [35]:
sample_matrix=np.array(([24,13,2,15],[15,2,54,65],[56,76,24,7]))
sample_matrix

array([[24, 13,  2, 15],
       [15,  2, 54, 65],
       [56, 76, 24,  7]])

In [44]:
sample_matrix[2][2]

24

In [37]:
sample_matrix[1][2]

54

In [40]:
sample_matrix[:,2]

array([ 2, 54, 24])

In [41]:
sample_matrix[1,1]

2

In [45]:
sample_matrix[1:3,2:4]

array([[54, 65],
       [24,  7]])

In [54]:
sample_matrix[1:,2:]

array([[54, 65],
       [24,  7]])

In [55]:
sample_matrix[2]

array([56, 76, 24,  7])

In [48]:
arrr=np.arange(10,100)
arrr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [51]:
arrr=arrr.reshape(6,15)
arrr

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [52]:
arrr[1:3,2:4]

array([[27, 28],
       [42, 43]])

In [53]:
arrr[3:8,3:6]

array([[58, 59, 60],
       [73, 74, 75],
       [88, 89, 90]])

#

In [56]:
sample_array=np.arange(1,31)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [57]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [58]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13])

In [59]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558])

In [61]:
np.log(sample_array) #takes log with base e i.e ln

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738])

In [62]:
np.max(sample_array)

30

In [64]:
np.min(sample_array)

1

In [63]:
np.argmax(sample_array)

29

In [65]:
np.argmin(sample_array)

0

In [66]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841, 900], dtype=int32)

In [67]:
np.std(sample_array)

8.65544144839919

In [68]:
np.var(sample_array)

74.91666666666667

In [69]:
np.mean(sample_array)

15.5

In [72]:
array=np.random.randn(3,4) ##normal distribution
array

array([[ 0.99007103,  1.02583904, -1.16571671,  0.06329299],
       [-1.55500428, -0.71645767,  1.71174195, -1.24453005],
       [-0.12834346,  0.83770905,  0.88364118,  1.05134438]])

In [75]:
np.round(array,decimals=3)

array([[ 0.99 ,  1.026, -1.166,  0.063],
       [-1.555, -0.716,  1.712, -1.245],
       [-0.128,  0.838,  0.884,  1.051]])

In [77]:
np.round(array,decimals=0)

array([[ 1.,  1., -1.,  0.],
       [-2., -1.,  2., -1.],
       [-0.,  1.,  1.,  1.]])

In [78]:
sports=np.array(['golf','cricket','fball','cricket','basketball'])
np.unique(sports)

array(['basketball', 'cricket', 'fball', 'golf'], dtype='<U10')

# Pandas

In [1]:
import pandas as pd

In [5]:
import numpy as np

In [3]:
labels=['a','b','c','d']
labels

['a', 'b', 'c', 'd']

In [4]:
list=[10,28,3,4]
list

[10, 28, 3, 4]

In [6]:
array=np.array([1,2,3,4])
array

array([1, 2, 3, 4])

In [7]:
dict={'w':10,'x':20,'y':30,'z':40}
dict

{'w': 10, 'x': 20, 'y': 30, 'z': 40}

In [8]:
pd.Series(data=list)

0    10
1    28
2     3
3     4
dtype: int64

In [9]:
pd.Series(data=list,index=labels)

a    10
b    28
c     3
d     4
dtype: int64

In [12]:
pd.Series(labels,list)

10    a
28    b
3     c
4     d
dtype: object

In [13]:
pd.Series(list,labels)

a    10
b    28
c     3
d     4
dtype: int64

In [14]:
pd.Series(dict)

w    10
x    20
y    30
z    40
dtype: int64

## Pandas dataframe and indexing

In [16]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [17]:
sports1['basketball']

3

In [18]:
sports2=pd.Series([11,13,12,4],index=['cricket','football','baseball','golf'])
sports2

cricket     11
football    13
baseball    12
golf         4
dtype: int64

In [19]:
sports1+sports2

baseball       NaN
basketball     NaN
cricket       12.0
football      15.0
golf           8.0
dtype: float64

In [23]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1

Score1    Score2    Score3    Score4    Score5
A  0.304299  0.372386  0.890421  0.945161  0.649373
B  0.251539  0.053929  0.955319  0.183100  0.963815
C  0.293160  0.036384  0.861480  0.017743  0.723279
D  0.566918  0.758043  0.201050  0.089733  0.186820
E  0.232275  0.240579  0.136346  0.596373  0.473166
F  0.380535  0.782922  0.559660  0.949077  0.704740
G  0.077263  0.614038  0.925524  0.793971  0.588066
H  0.784368  0.713104  0.744212  0.998442  0.427742

In [24]:
df1[['Score2','Score1','Score5']]

Score2    Score1    Score5
A  0.372386  0.304299  0.649373
B  0.053929  0.251539  0.963815
C  0.036384  0.293160  0.723279
D  0.758043  0.566918  0.186820
E  0.240579  0.232275  0.473166
F  0.782922  0.380535  0.704740
G  0.614038  0.077263  0.588066
H  0.713104  0.784368  0.427742

In [25]:
df1['Score6']=df1['Score1']-df1['Score2']
df1

Score1    Score2    Score3    Score4    Score5    Score6
A  0.304299  0.372386  0.890421  0.945161  0.649373 -0.068086
B  0.251539  0.053929  0.955319  0.183100  0.963815  0.197610
C  0.293160  0.036384  0.861480  0.017743  0.723279  0.256776
D  0.566918  0.758043  0.201050  0.089733  0.186820 -0.191125
E  0.232275  0.240579  0.136346  0.596373  0.473166 -0.008304
F  0.380535  0.782922  0.559660  0.949077  0.704740 -0.402388
G  0.077263  0.614038  0.925524  0.793971  0.588066 -0.536775
H  0.784368  0.713104  0.744212  0.998442  0.427742  0.071264

In [26]:
df1.drop('Score5',axis=1)

Score1    Score2    Score3    Score4    Score6
A  0.304299  0.372386  0.890421  0.945161 -0.068086
B  0.251539  0.053929  0.955319  0.183100  0.197610
C  0.293160  0.036384  0.861480  0.017743  0.256776
D  0.566918  0.758043  0.201050  0.089733 -0.191125
E  0.232275  0.240579  0.136346  0.596373 -0.008304
F  0.380535  0.782922  0.559660  0.949077 -0.402388
G  0.077263  0.614038  0.925524  0.793971 -0.536775
H  0.784368  0.713104  0.744212  0.998442  0.071264

In [27]:
df1.drop('E')

Score1    Score2    Score3    Score4    Score5    Score6
A  0.304299  0.372386  0.890421  0.945161  0.649373 -0.068086
B  0.251539  0.053929  0.955319  0.183100  0.963815  0.197610
C  0.293160  0.036384  0.861480  0.017743  0.723279  0.256776
D  0.566918  0.758043  0.201050  0.089733  0.186820 -0.191125
F  0.380535  0.782922  0.559660  0.949077  0.704740 -0.402388
G  0.077263  0.614038  0.925524  0.793971  0.588066 -0.536775
H  0.784368  0.713104  0.744212  0.998442  0.427742  0.071264

In [76]:
df2={'ID':[101,102,103,107,176],'Name':['Prerana','Akanksha','Juhi','Anku','Deepak'],'Profit':[20,54,56,87,123]}
df=pd.DataFrame(df2)
df

ID      Name  Profit
0  101   Prerana      20
1  102  Akanksha      54
2  103      Juhi      56
3  107      Anku      87
4  176    Deepak     123

## Assesment
1. Create a null vector of size 10.
2. Create a null vector of size 10 but the fifth value should be one.
3. Create a vector with values rangining from 10 to 65.
4. Reverse the above vector.
5. Create a 3X3 matrix with values ranging from 0 to 8.



In [39]:
#1
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [40]:
#2
null_vector1=np.zeros(10)
null_vector1[4]=1
null_vector1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [48]:
#3
vector=np.arange(10,66)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65])

In [64]:
#4
vector[::-1]

array([65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [63]:
#4
rev_vector=np.arange(65,9,-1)
rev_vector

array([65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [71]:
#5
matrix=np.arange(0,9)
matrix.reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [73]:
matrix1=np.arange(0,9).reshape(3,3)
matrix1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [80]:
matrix2=np.arange(9).reshape(3,3)
matrix2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [85]:
x = np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
